### PR TITLE
Pagination bug

### LINKED ISSUE #19: Pagination bug
There is a bug in the datasets list and users list pagination: when we have more than 6 datasets or more than 5 users, changing to the second page and returning to the first one will make all datasets/users appear in the first page, and the second one will be emptied.

### PR DESCRIPTION
**Pull request by ger4rdgg**
solved pagination bug involving datasets and users lists

### CODE REVIEW

File: src/app/dataset/dataset-list/dataset-list.component.ts [hunk 1]
```diff
@@ -24,17 +24,11 @@ export class DatasetListComponent implements OnInit {
               private authenticationBasicService: AuthenticationBasicService) { }
 
   ngOnInit(): void {
-    this.datasetService.getAll({size: this.pageSize, sort: this.sorting}).subscribe(
```
Comment (bergacat1) [inline src/app/dataset/dataset-list/dataset-list.component.ts:27]: Leaving this line as:
`this.datasetService.getAll({size: this.pageSize, sort: this.sorting, params: [{key: 'page', value: 0}]}).subscribe(`
Seems to solve the problem.

**Review by bergacat1 — COMMENTED** [review]
With your solution, we would be loading all Datasets from the database in memory and not benefiting from the paging functionality of the API. The error seems to be produced by a bug of the `ngx-hal-client`. However, I've managed to find a workaround to the error that seems to work fine.
